<?php

class RebelShip extends AbstractShip
{

    public function getFavoriteJedi()
    {

        $coolJedi = array('Yoda', 'Ben Kenobi');
        $key = array_rand($coolJedi);

        return $coolJedi[$key];

    }

    public function getType(): string
    {
        return 'Rebel';
    }

    public function isFunctional(): bool
    {
        return true;
    }

    // overwritten function
    public function getNameAndSpecs($useShortFormat = false)
    {
        $val = parent::getNameAndSpecs($useShortFormat); // TODO: Change the autogenerated stub
        $val .= ' (Called by Rebel Child-Class)';

        return $val;

    }

    /**
     * @inheritDoc
     */
    public function getJediFactor()
    {
        return rand(10,30);
    }
}